### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Echoxixixi** [Jason-Woo/-MPI-KNN-#1]
你好，我是初学者，我跑你的代码的时候遇到了这个问题
![image](https://user-images.githubusercontent.com/83957667/147339655-1c10b235-a726-4d11-a59e-726c7bed56cb.png)
请问是怎么回事啊

**Comment by Jason-Woo** [comment]
您好，可能产生“未申明的标识符”的原因有很多，根据你提供的信息很难看出来
请检查头文件的引用是否正确，以及编译环境是否可以编译运行其他的c++文件
如果都没有问题的话尝试在申明这些指针的时候给他们赋一个初始值
